openapi: 3.0.3
info:
  title: Inspectr Authenticated API Example
  version: 1.0.0
  description: |
    Spin up a mock backend from any OpenAPI — zero config.
    A minimal API example for Mocking APIs with Authentication in Inspectr.
paths:
  /basic-auth-protected:
    get:
      security:
        - basicAuth: []
      responses:
        '200':
          description: Protected resource
          content:
            application/json:
              example:
                message: OK
        '401':
          description: Unauthorized
  /api-key-protected:
    get:
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              example:
                message: OK
        '401':
          description: Unauthorized
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
