openapi: 3.1.0
info:
  title: Inspectr Hello World API
  version: "1.0.0"
  description: |
    Spin up a mock backend from any OpenAPI — zero config.
    A minimal API example for Mocking APIs in Inspectr.
servers:
  - url: http://localhost:8080
paths:
  /:
    get:
      summary: Hello World endpoint
      description: Returns a greeting message from Inspectr.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Hello, World! Powered by Inspectr 🚀"
